-- 4.5.9
-- 1
CREATE TABLE EXAM_MARKS2(
    EXAM_ID INTEGER NOT NULL,
    SUBJ_ID INTEGER NOT NULL,
    STUDENT_ID INTEGER NOT NULL,
    MARK INTEGER,
    EXAM_DATE DATE NOT NULL,
    CONSTRAINT EXAM_MARKS_CONSTR_1 UNIQUE (EXAM_ID, SUBJ_ID, STUDENT_ID),
    CONSTRAINT EXAM_MARKS_CONSTR_2 UNIQUE (EXAM_ID, EXAM_DATE)
);
-- 2
CREATE TABLE SUBJECT2(
    SUBJ_ID INTEGER PRIMARY KEY,
    SUBJ_NAME CHAR(25),
    HOUR INTEGER DEFAULT 36 NOT NULL,
    SEMESTER INTEGER CHECK (
        SEMESTER BETWEEN 1 AND 12
    )
);
-- 3
CREATE TABLE EXAM_MARKS3(
    EXAM_ID INTEGER NOT NULL,
    SUBJ_ID INTEGER NOT NULL,
    STUDENT_ID INTEGER NOT NULL,
    CONSTRAINT EXAM_MARKS_CHECK CHECK (
        (
            (EXAM_ID > SUBJ_ID)
            AND (SUBJ_ID > STUDENT_ID)
        )
    )
);