CREATE TABLE STUDENT1(
    STUDENT_ID SERIAL PRIMARY KEY,
    SURNAME VARCHAR(200),
    NAME VARCHAR(200),
    STIPEND INTEGER,
    KURS INTEGER,
    CITY VARCHAR(200),
    BIRTHDAY DATE,
    UNIV_ID INTEGER,
    FOREIGN KEY (UNIV_ID) REFERENCES UNIVERSITY(UNIV_ID)
);
CREATE TABLE SUBJECT1(
    SUBJ_ID SERIAL PRIMARY KEY,
    SUBJ_NAME VARCHAR(200) NOT NULL,
    HOUR INTEGER NOT NULL,
    SEMESTER INTEGER NOT NULL
);
INSERT INTO subject1
SELECT *
FROM subject;